### ISSUE TITLE
[13972] Failed to execute script postman_doc_gen

### ISSUE THREAD

**Issue by 2adnan** [karthiks3000/postman-doc-gen#2]
Traceback (most recent call last):
  File "postman_doc_gen\postman_doc_gen.py", line 27, in <module>
  File "postman_doc_gen\document_generator.py", line 35, in generate_doc
  File "postman_doc_gen\document_generator.py", line 104, in validate_collection
  File "site-packages\fastjsonschema\__init__.py", line 105, in validate
  File "<string>", line 10, in validate_https___schema_getpostman_com_json_collection_v2_1_0
fastjsonschema.exceptions.JsonSchemaException: data must contain ['info', 'item'] properties
[13972] Failed to execute script postman_doc_gen

**Comment by 2adnan** [comment]
This is the error with v2.1 collection:

Traceback (most recent call last):
  File "postman_doc_gen\postman_doc_gen.py", line 27, in <module>
  File "postman_doc_gen\document_generator.py", line 48, in generate_doc
  File "postman_doc_gen\document_generator.py", line 166, in add_items
  File "postman_doc_gen\document_generator.py", line 166, in add_items
  File "postman_doc_gen\document_generator.py", line 166, in add_items
  File "postman_doc_gen\document_generator.py", line 179, in add_items
  File "postman_doc_gen\document_generator.py", line 201, in add_apis
  File "postman_doc_gen\document_generator.py", line 230, in get_examples
TypeError: must be str, not NoneType
[34608] Failed to execute script postman_doc_gen

**Comment by karthiks3000** [comment]
@2adnan  Can you provide a sample collection that this can be reproduced with?

**Comment by 2adnan** [comment]
please see attached.
[collection.zip](https://github.com/karthiks3000/postman-doc-gen/files/4801678/collection.zip)

**Comment by karthiks3000** [comment]
@2adnan  I've fixed the issue with a new release - 
https://github.com/karthiks3000/postman-doc-gen/releases/tag/v1.0.2

Tested and confirmed with the v2.1 collection
