### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\xd7' in position 1775: character maps to <undefined>

### ISSUE THREAD

**Issue by kadyrkulovr** [karthiks3000/postman-doc-gen#21]
What do I need to fix in my exported collection? I don't have any special characters. Thank you.

full text:
Traceback (most recent call last):
  File "postman_doc_gen.py", line 29, in <module>
  File "document_generator.py", line 80, in generate_doc
  File "c:\users\karth\documents\code\python\postman-doc\venv\lib\encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xd7' in position 1775: character maps to <undefined>
[10844] Failed to execute script postman_doc_gen

**Comment by JhomeWu** [comment]
This problem can be solved by PR #26 
Or you can just setup [Python UTF-8 Mode](https://docs.python.org/3/library/os.html#utf8-mode)
