### ISSUE TITLE
  File "c:\users\karth\documents\code\python\postman-doc\venv\lib\encodings\cp1252.py", line 23, in decode UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 35969: character maps to <undefined> [17992] Failed to execute script postman_doc_gen

### ISSUE THREAD

**Issue by shahind** [karthiks3000/postman-doc-gen#23]
running 
```
 .\postman_doc_gen.exe .\collection.json -o .\Html 
``` 
results in 
``` 
Traceback (most recent call last):
  File "postman_doc_gen.py", line 29, in <module>
  File "document_generator.py", line 41, in generate_doc
  File "document_generator.py", line 123, in validate_collection
  File "document_generator.py", line 110, in get_json_file
  File "json\__init__.py", line 296, in load
  File "c:\users\karth\documents\code\python\postman-doc\venv\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 35969: character maps to <undefined>
[17144] Failed to execute script postman_doc_gen
```

**Comment by JhomeWu** [comment]
This problem can be solved by PR #26 
Or you can just download repo and follow step setup locally then use it in [Python UTF-8 Mode](https://docs.python.org/3/library/os.html#utf8-mode)
